# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d34c9c87fe5afb2760126a2baf2425af8c846b7757651aa9a43b6fe2fe957fa1697c5f0154ff75347b7226088151009ea7a68fd713f5b7b42a67fae85f13974f

test:
  secret_key_base: 21113a987edd4e334a522ffee0bb846d3f85a89553b455870f1a1c1410cb8d43b709850c5441a7331df2e3d1f9d7dff2e6e4ad0f67181d679f97cddf3cfb6db4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
